### ISSUE TITLE
Update documentation for harvesting PDS3 data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#10]
EDIT: I figured it out: I had to put the target directory on the command-line. I don't know whether the documentation or the code should be fixed.

----

ORIGINAL ISSUE:

I easily could be doing something wrong that I can't figure out.

% harvest -C /PDS4tools/harvest/conf/search/defaults -o /PDS4tools -c /Users/rchen/Desktop/killme.xml
java.lang.NullPointerException
	at gov.nasa.pds.harvest.search.crawler.metadata.extractor.Pds3MetExtractorConfig.<init>(Pds3MetExtractorConfig.java:44)
	at gov.nasa.pds.harvest.search.HarvesterSearch.harvest(HarvesterSearch.java:229)
	at gov.nasa.pds.harvest.search.HarvestSearchLauncher.doHarvesting(HarvestSearchLauncher.java:497)
	at gov.nasa.pds.harvest.search.HarvestSearchLauncher.processMain(HarvestSearchLauncher.java:601)
	at gov.nasa.pds.harvest.search.HarvestSearchLauncher.main(HarvestSearchLauncher.java:620)
null
******* The optimized code generation is disabled ************
PDS Harvest Tool Log
Version                     Version 2.5.2
Time                        Tue, Oct 29 2019 at 04:02:18 PM
Target(s)                   [/Users/rchen/Desktop/test/testHarv/DAWNGRAND1B/DATA]
Target Type                 PDS3
File Inclusions             [*.LBL]
Severity Level              INFO
Config directory            /PDS4tools/harvest/conf/search/defaults
Output directory            /PDS4tools/solr-docs
Transaction ID              d5bb8905-4cd3-473c-a8ca-a4fcde971495
INFO:   XML extractor set to the following default namespace: http://pds.nasa.gov/pds4/pds/v1
Summary:
0 of 0 file(s) processed, 0 other file(s) skipped
0 error(s), 0 warning(s)
Product Labels:
0          Successfully registered  
0          Failed to register       
Search Service Solr Documents:
0          Successfully created     
0          Failed to get created    
XPath Solr Documents (Quick Look Only, Ignore Failed Ingestions):
0          Successfully registered  
0          Failed to register       
Product Types Handled:
Registry Package Id: N/A
% 
% 
% ls -Rl /PDS4tools/harvest/conf/search/defaults
total 0
drwxr-xr-x@ 4 rchen  JPL\Domain Users  128 Oct 29 12:18 pds/
drwxr-xr-x@ 3 rchen  JPL\Domain Users   96 Oct 29 12:18 psa/
/PDS4tools/harvest/conf/search/defaults/pds:
total 0
drwxr-xr-x@ 13 rchen  JPL\Domain Users  416 Oct 29 12:18 pds3/
drwxr-xr-x@ 26 rchen  JPL\Domain Users  832 Oct 29 12:18 pds4/
/PDS4tools/harvest/conf/search/defaults/pds/pds3:
total 128
-rw-r--r--@ 1 rchen  JPL\Domain Users  7313 Oct 29 12:18 attribute.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  5245 Oct 29 12:18 class.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  4286 Oct 29 12:18 context.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   139 Oct 29 12:18 core.properties
-rw-r--r--@ 1 rchen  JPL\Domain Users  5905 Oct 29 12:18 dataset.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  3469 Oct 29 12:18 instrument.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  3321 Oct 29 12:18 instrumenthost.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  3532 Oct 29 12:18 investigation.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  3069 Oct 29 12:18 proxy.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  6171 Oct 29 12:18 service.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  3217 Oct 29 12:18 target.xml
/PDS4tools/harvest/conf/search/defaults/pds/pds4:
total 328
-rw-r--r--@ 1 rchen  JPL\Domain Users   3509 Oct 29 12:18 ancillary.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   9118 Oct 29 12:18 attribute.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   7850 Oct 29 12:18 browse.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   9593 Oct 29 12:18 bundle.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   7046 Oct 29 12:18 class.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   9346 Oct 29 12:18 collection.xml
drwxr-xr-x@ 6 rchen  JPL\Domain Users    192 Oct 29 12:18 context/
-rw-r--r--@ 1 rchen  JPL\Domain Users  11887 Oct 29 12:18 context.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users    130 Oct 29 12:18 core.properties
-rw-r--r--@ 1 rchen  JPL\Domain Users   3938 Oct 29 12:18 dip.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   3964 Oct 29 12:18 dip_deep_archive.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   8787 Oct 29 12:18 document.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   7842 Oct 29 12:18 file_text.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   6629 Oct 29 12:18 native.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   8807 Oct 29 12:18 observational.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   6858 Oct 29 12:18 service.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   3938 Oct 29 12:18 sip.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   4041 Oct 29 12:18 sip_deep_archive.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   3535 Oct 29 12:18 software.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   6641 Oct 29 12:18 spice_kernel.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   3418 Oct 29 12:18 thumbnail.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   3292 Oct 29 12:18 update.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   3420 Oct 29 12:18 xml_schema.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users   2379 Oct 29 12:18 zipped.xml
/PDS4tools/harvest/conf/search/defaults/pds/pds4/context:
total 32
-rw-r--r--@ 1 rchen  JPL\Domain Users  2197 Oct 29 12:18 instrument-host.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  1947 Oct 29 12:18 instrument.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  2441 Oct 29 12:18 investigation.xml
-rw-r--r--@ 1 rchen  JPL\Domain Users  1392 Oct 29 12:18 target.xml
/PDS4tools/harvest/conf/search/defaults/psa:
total 0
drwxr-xr-x@ 4 rchen  JPL\Domain Users  128 Oct 29 12:18 pds3/
/PDS4tools/harvest/conf/search/defaults/psa/pds3:
total 24
-rw-r--r--@ 1 rchen  JPL\Domain Users   138 Oct 29 12:18 core.properties
-rw-r--r--@ 1 rchen  JPL\Domain Users  4926 Oct 29 12:18 dataset.xml
%
%
% ls -lR /PDS4tools/solr-docs/
%
%
% ls -l /Users/rchen/Desktop/killme.xml                -rw-r--r--  1 rchen  JPL\Domain Users  3600 Oct 29 16:02 /Users/rchen/Desktop/killme.xml
%
%
% ls -l /Users/rchen/Desktop/test/testHarv/DAWNGRAND1B/DATA
total 10256
-rw-r--r--  1 rchen  JPL\Domain Users     5497 Oct 19  2016 GRD-L1B-151023-151216_160816-CTL-BGOC.LBL
-rw-r--r--  1 rchen  JPL\Domain Users    12376 Oct 19  2016 GRD-L1B-151023-151216_160816-CTL-BGOC.TAB
-rw-r--r--@ 1 rchen  JPL\Domain Users    39840 Sep 13  2016 GRD-L1B-151023-151216_160816-EPG.LBL
-rw-r--r--@ 1 rchen  JPL\Domain Users  5184439 Aug 16  2016 GRD-L1B-151023-151216_160816-EPG.TAB
%
%
% cat /Users/rchen/Desktop/killme.xml
<?xml version="1.0" encoding="UTF-8"?>

<policy xmlns="https://pds.nasa.gov/software/pds4/harvest/v1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:harvest="https://pds.nasa.gov/software/pds4/harvest/v1"
  xsi:schemaLocation="https://pds.nasa.gov/software/pds4/harvest/v1 https://pds.nasa.gov/software/pds4/harvest/v1/harvest-policy.xsd">

  
  <pds3Directories>
    <path>/Users/rchen/Desktop/test/testHarv/DAWNGRAND1B/DATA</path>
    <fileFilter>
      <include>*.LBL</include>
    </fileFilter>
  </pds3Directories>

  <accessUrls harvest:registerFileUrls="false">
    <accessUrl>
      <baseUrl>http://starbase.jpl.nasa.gov</baseUrl>
      <offset>$HOME</offset>
    </accessUrl>
  </accessUrls>

  

  <candidates>
    
    <pds3ProductMetadata>
      
      <lidContents harvest:prefix="urn:nasa:pds" harvest:appendFilename="true">
        <elementName>DATA_SET_ID</elementName>
      </lidContents>

      
      <titleContents harvest:appendFilename="true">
        <elementName>DATA_SET_ID</elementName>
      </titleContents>

      
      <staticMetadata>
        <slot harvest:name="information_model_version">
          <value>1.11.0.0</value>
        </slot>
        <slot harvest:name="product_class">
          <value>Product_Proxy_PDS3</value>
        </slot>
        <slot harvest:name="data_set_ref">
          <value>urn:nasa:pds:context_pds3:data_set:data_set.vg2-j-pls-5-summ-ele-mom-96.0sec-v1.0</value>
        </slot>
        <slot harvest:name="investigation_ref">
          <value>urn:nasa:pds:context_pds3:investigation:mission.voyager</value>
        </slot>
        <slot harvest:name="instrument_host_ref">
          <value>urn:nasa:pds:context_pds3:instrument_host:instrument_host.vg2</value>
        </slot>
        <slot harvest:name="instrument_ref">
          <value>urn:nasa:pds:context_pds3:instrument:instrument.pls_vg2</value>
        </slot>
        <slot harvest:name="target_ref">
          <value>urn:nasa:pds:context_pds3:target:target.planet.jupiter</value>
        </slot>
      </staticMetadata>

      
      <ancillaryMetadata>
        <elementName harvest:slotName="observation_start_date_time">
          START_TIME
        </elementName>
        <elementName harvest:slotName="observation_stop_date_time">
          STOP_TIME
        </elementName>
        <elementName harvest:slotName="product_type">
          PRODUCT_TYPE
        </elementName>
        <elementName harvest:slotName="creation_date_time">
          PRODUCT_CREATION_TIME
        </elementName>
        <elementName harvest:slotName="encoding_type">
          INTERCHANGE_FORMAT
        </elementName>
      </ancillaryMetadata>
    </pds3ProductMetadata>
  </candidates>
</policy>

**Comment by jordanpadams** [comment]
this is for deprecated harvest app. closing as wontfix or will address with internal workarounds as needed
